sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t x78240/docker-react -f Dockerfile.dev .  


script:
  - docker run -e CI=true x78240/docker-react npm run test